package dev.ryoung.ui;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.EventQueue;
import java.awt.Font;
import java.awt.Frame;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.BorderFactory;
import javax.swing.DefaultComboBoxModel;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.WindowConstants;
import javax.swing.border.BevelBorder;

import dev.ryoung.classes.Recipe;

/**
 * Initial comments
 * 
 * @author ryoung
 */
public class AddRecipe extends JDialog {

    /**
     * Creates new form AddRecipe
     */
    public AddRecipe(Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        scrollPane = new JScrollPane();
        mainPanel = new JPanel();
        headerPanel = new JPanel();
        headerText = new JLabel();
        recipeName = new JLabel();
        nameText = new JTextField();
        recipeCategory = new JLabel();
        categoryBox = new JComboBox<>();
        ingredients = new JLabel();
        ingredientsPanel = new JPanel();
        amountText1 = new JTextField();
        measurementBox1 = new JComboBox<>();
        ingredientText1 = new JTextField();
        amountText2 = new JTextField();
        measurementBox2 = new JComboBox<>();
        ingredientText2 = new JTextField();
        amountText3 = new JTextField();
        measurementBox3 = new JComboBox<>();
        ingredientText3 = new JTextField();
        amountText4 = new JTextField();
        measurementBox4 = new JComboBox<>();
        ingredientText4 = new JTextField();
        amountText5 = new JTextField();
        measurementBox5 = new JComboBox<>();
        ingredientText5 = new JTextField();
        amountText6 = new JTextField();
        measurementBox6 = new JComboBox<>();
        ingredientText6 = new JTextField();
        amountText7 = new JTextField();
        measurementBox7 = new JComboBox<>();
        ingredientText7 = new JTextField();
        amountText8 = new JTextField();
        measurementBox8 = new JComboBox<>();
        ingredientText8 = new JTextField();
        amountText9 = new JTextField();
        measurementBox9 = new JComboBox<>();
        ingredientText9 = new JTextField();
        amountText10 = new JTextField();
        measurementBox10 = new JComboBox<>();
        ingredientText10 = new JTextField();
        amountText11 = new JTextField();
        measurementBox11 = new JComboBox<>();
        ingredientText11 = new JTextField();
        amountText12 = new JTextField();
        measurementBox12 = new JComboBox<>();
        ingredientText12 = new JTextField();
        amountText13 = new JTextField();
        measurementBox13 = new JComboBox<>();
        ingredientText13 = new JTextField();
        amountText14 = new JTextField();
        measurementBox14 = new JComboBox<>();
        ingredientText14 = new JTextField();
        amountText15 = new JTextField();
        measurementBox15 = new JComboBox<>();
        ingredientText15 = new JTextField();
        addButton = new JButton();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new Dimension(800, 650));
        setMinimumSize(new Dimension(800, 650));
        setPreferredSize(new Dimension(800, 650));

        mainPanel.setBackground(new Color(51, 51, 51));

        headerPanel.setBackground(new Color(153, 0, 0));
        headerPanel.setBorder(BorderFactory.createBevelBorder(BevelBorder.RAISED));

        headerText.setFont(new Font("Chalkduster", 1, 36)); 
        headerText.setForeground(new Color(255, 255, 255));
        headerText.setText("A New Recipe");

        GroupLayout headerPanelLayout = new GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, headerPanelLayout.createSequentialGroup()
                .addContainerGap(203, Short.MAX_VALUE)
                .addComponent(headerText)
                .addGap(193, 193, 193))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(headerText)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        recipeName.setFont(new Font("Tahoma", 0, 18)); 
        recipeName.setForeground(new Color(255, 255, 255));
        recipeName.setText("Recipe Name");

        recipeCategory.setFont(new Font("Tahoma", 0, 18)); 
        recipeCategory.setForeground(new Color(255, 255, 255));
        recipeCategory.setText("Category");

        ingredients.setFont(new Font("Tahoma", 0, 18)); 
        ingredients.setForeground(new Color(255, 255, 255));
        ingredients.setText("Ingredients");

        Font font = new Font("Tahoma", 0, 14);
        
        categoryBox.setFont(font); 
        categoryBox.setModel(new DefaultComboBoxModel<>(new String[] { "Beef", "Chicken", "Pork", "Fish", "Dessert", "Breakfast", "Other" }));

        nameText.setFont(font); 

        ingredientsPanel.setBackground(new Color(51, 51, 51));

        amountText1.setFont(font); 
        measurementBox1.setModel(new DefaultComboBoxModel<>(new String[] { "pound", "ounce", "cup", "teaspoon", "tablespoon", "box", "bag", "jar", "unit" }));
        ingredientText1.setFont(font); 

        amountText2.setFont(font); 
        measurementBox2.setModel(new DefaultComboBoxModel<>(new String[] { "pound", "ounce", "cup", "teaspoon", "tablespoon", "box", "bag", "jar", "unit" }));
        ingredientText2.setFont(font); 

        amountText3.setFont(font); 
        measurementBox3.setModel(new DefaultComboBoxModel<>(new String[] { "pound", "ounce", "cup", "teaspoon", "tablespoon", "box", "bag", "jar", "unit" }));
        ingredientText3.setFont(font); 

        amountText4.setFont(font); 
        measurementBox4.setModel(new DefaultComboBoxModel<>(new String[] { "pound", "ounce", "cup", "teaspoon", "tablespoon", "box", "bag", "jar", "unit" }));
        ingredientText4.setFont(font); 
        
        amountText5.setFont(font); 
        measurementBox5.setModel(new DefaultComboBoxModel<>(new String[] { "pound", "ounce", "cup", "teaspoon", "tablespoon", "box", "bag", "jar", "unit" }));
        ingredientText5.setFont(font); 
        
        amountText6.setFont(font); 
        measurementBox6.setModel(new DefaultComboBoxModel<>(new String[] { "pound", "ounce", "cup", "teaspoon", "tablespoon", "box", "bag", "jar", "unit" }));
        ingredientText6.setFont(font); 
        
        amountText7.setFont(font); 
        measurementBox7.setModel(new DefaultComboBoxModel<>(new String[] { "pound", "ounce", "cup", "teaspoon", "tablespoon", "box", "bag", "jar", "unit" }));
        ingredientText7.setFont(font); 
        
        amountText8.setFont(font); 
        measurementBox8.setModel(new DefaultComboBoxModel<>(new String[] { "pound", "ounce", "cup", "teaspoon", "tablespoon", "box", "bag", "jar", "unit" }));
        ingredientText8.setFont(font); 

        amountText9.setFont(font); 
        measurementBox9.setModel(new DefaultComboBoxModel<>(new String[] { "pound", "ounce", "cup", "teaspoon", "tablespoon", "box", "bag", "jar", "unit" }));
        ingredientText9.setFont(font);
        
        amountText10.setFont(font); 
        measurementBox10.setModel(new DefaultComboBoxModel<>(new String[] { "pound", "ounce", "cup", "teaspoon", "tablespoon", "box", "bag", "jar", "unit" }));
        ingredientText10.setFont(font);
        
        amountText11.setFont(font); 
        measurementBox11.setModel(new DefaultComboBoxModel<>(new String[] { "pound", "ounce", "cup", "teaspoon", "tablespoon", "box", "bag", "jar", "unit" }));
        ingredientText11.setFont(font);
        
        amountText12.setFont(font); 
        measurementBox12.setModel(new DefaultComboBoxModel<>(new String[] { "pound", "ounce", "cup", "teaspoon", "tablespoon", "box", "bag", "jar", "unit" }));
        ingredientText12.setFont(font);
        
        amountText13.setFont(font); 
        measurementBox13.setModel(new DefaultComboBoxModel<>(new String[] { "pound", "ounce", "cup", "teaspoon", "tablespoon", "box", "bag", "jar", "unit" }));
        ingredientText13.setFont(font);
        
        amountText14.setFont(font); 
        measurementBox14.setModel(new DefaultComboBoxModel<>(new String[] { "pound", "ounce", "cup", "teaspoon", "tablespoon", "box", "bag", "jar", "unit" }));
        ingredientText14.setFont(font);
        
        amountText15.setFont(font); 
        measurementBox15.setModel(new DefaultComboBoxModel<>(new String[] { "pound", "ounce", "cup", "teaspoon", "tablespoon", "box", "bag", "jar", "unit" }));
        ingredientText15.setFont(font);
       

        GroupLayout ingredientsPanelLayout = new GroupLayout(ingredientsPanel);
        ingredientsPanel.setLayout(ingredientsPanelLayout);
        ingredientsPanelLayout.setHorizontalGroup(
            ingredientsPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, ingredientsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ingredientsPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(ingredientsPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                        .addGroup(ingredientsPanelLayout.createSequentialGroup()
                            .addComponent(amountText1, GroupLayout.PREFERRED_SIZE, 67, GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(measurementBox1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(ingredientText1))
                        .addGroup(ingredientsPanelLayout.createSequentialGroup()
                            .addComponent(amountText2, GroupLayout.PREFERRED_SIZE, 67, GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(measurementBox2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(ingredientText2, GroupLayout.PREFERRED_SIZE, 250, GroupLayout.PREFERRED_SIZE))
                        .addGroup(ingredientsPanelLayout.createSequentialGroup()
                            .addComponent(amountText3, GroupLayout.PREFERRED_SIZE, 67, GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(measurementBox3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(ingredientText3, GroupLayout.PREFERRED_SIZE, 250, GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ingredientsPanelLayout.createSequentialGroup()
                        .addComponent(amountText4, GroupLayout.PREFERRED_SIZE, 67, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(measurementBox4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ingredientText4, GroupLayout.PREFERRED_SIZE, 250, GroupLayout.PREFERRED_SIZE))
                    .addGroup(ingredientsPanelLayout.createSequentialGroup()
                        .addComponent(amountText5, GroupLayout.PREFERRED_SIZE, 67, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(measurementBox5, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ingredientText5, GroupLayout.PREFERRED_SIZE, 250, GroupLayout.PREFERRED_SIZE))
                    .addGroup(ingredientsPanelLayout.createSequentialGroup()
                        .addComponent(amountText6, GroupLayout.PREFERRED_SIZE, 67, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(measurementBox6, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ingredientText6, GroupLayout.PREFERRED_SIZE, 250, GroupLayout.PREFERRED_SIZE))
                    .addGroup(ingredientsPanelLayout.createSequentialGroup()
                        .addComponent(amountText7, GroupLayout.PREFERRED_SIZE, 67, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(measurementBox7, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ingredientText7, GroupLayout.PREFERRED_SIZE, 250, GroupLayout.PREFERRED_SIZE))
                    .addGroup(ingredientsPanelLayout.createSequentialGroup()
                        .addComponent(amountText8, GroupLayout.PREFERRED_SIZE, 67, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(measurementBox8, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ingredientText8, GroupLayout.PREFERRED_SIZE, 250, GroupLayout.PREFERRED_SIZE))
                    .addGroup(ingredientsPanelLayout.createSequentialGroup()
                        .addComponent(amountText9, GroupLayout.PREFERRED_SIZE, 67, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(measurementBox9, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ingredientText9, GroupLayout.PREFERRED_SIZE, 250, GroupLayout.PREFERRED_SIZE))
                    .addGroup(ingredientsPanelLayout.createSequentialGroup()
                        .addComponent(amountText10, GroupLayout.PREFERRED_SIZE, 67, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(measurementBox10, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ingredientText10, GroupLayout.PREFERRED_SIZE, 250, GroupLayout.PREFERRED_SIZE))
                    .addGroup(ingredientsPanelLayout.createSequentialGroup()
                        .addComponent(amountText11, GroupLayout.PREFERRED_SIZE, 67, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(measurementBox11, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ingredientText11, GroupLayout.PREFERRED_SIZE, 250, GroupLayout.PREFERRED_SIZE))
                    .addGroup(ingredientsPanelLayout.createSequentialGroup()
                        .addComponent(amountText12, GroupLayout.PREFERRED_SIZE, 67, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(measurementBox12, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ingredientText12, GroupLayout.PREFERRED_SIZE, 250, GroupLayout.PREFERRED_SIZE))
                    .addGroup(ingredientsPanelLayout.createSequentialGroup()
                        .addComponent(amountText13, GroupLayout.PREFERRED_SIZE, 67, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(measurementBox13, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ingredientText13, GroupLayout.PREFERRED_SIZE, 250, GroupLayout.PREFERRED_SIZE))
                    .addGroup(ingredientsPanelLayout.createSequentialGroup()
                        .addComponent(amountText14, GroupLayout.PREFERRED_SIZE, 67, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(measurementBox14, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ingredientText14, GroupLayout.PREFERRED_SIZE, 250, GroupLayout.PREFERRED_SIZE))
                    .addGroup(ingredientsPanelLayout.createSequentialGroup()
                        .addComponent(amountText15, GroupLayout.PREFERRED_SIZE, 67, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(measurementBox15, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ingredientText15, GroupLayout.PREFERRED_SIZE, 250, GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(214, Short.MAX_VALUE))
        );
        ingredientsPanelLayout.setVerticalGroup(
            ingredientsPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(ingredientsPanelLayout.createSequentialGroup()
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ingredientsPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(amountText1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(measurementBox1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(ingredientText1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ingredientsPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(amountText2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(measurementBox2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(ingredientText2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ingredientsPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(amountText3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(measurementBox3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(ingredientText3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ingredientsPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(amountText4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(measurementBox4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(ingredientText4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ingredientsPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(amountText5, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(measurementBox5, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(ingredientText5, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ingredientsPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(amountText6, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(measurementBox6, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(ingredientText6, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ingredientsPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(amountText7, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(measurementBox7, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(ingredientText7, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ingredientsPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(amountText8, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(measurementBox8, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(ingredientText8, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ingredientsPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(amountText9, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(measurementBox9, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(ingredientText9, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ingredientsPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(amountText10, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(measurementBox10, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(ingredientText10, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ingredientsPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(amountText11, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(measurementBox11, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(ingredientText11, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ingredientsPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(amountText12, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(measurementBox12, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(ingredientText12, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ingredientsPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(amountText13, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(measurementBox13, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(ingredientText13, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ingredientsPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(amountText14, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(measurementBox14, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(ingredientText14, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ingredientsPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(amountText15, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(measurementBox15, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(ingredientText15, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
        );

        addButton.setBackground(new Color(153, 0, 0));
        addButton.setFont(new Font("Tahoma", 0, 18)); 
        addButton.setText("Add Recipe");
        addButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        GroupLayout mainPanelLayout = new GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(addButton, GroupLayout.PREFERRED_SIZE, 130, GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(mainPanelLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(categoryBox, GroupLayout.PREFERRED_SIZE, 250, GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameText, GroupLayout.PREFERRED_SIZE, 250, GroupLayout.PREFERRED_SIZE))
                        .addGap(281, 281, 281))
                    .addGroup(mainPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addComponent(recipeName)
                        .addComponent(headerPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addComponent(recipeCategory)
                        .addComponent(ingredients)
                        .addComponent(ingredientsPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(headerPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(mainPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(recipeName)
                    .addComponent(nameText, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(recipeCategory)
                    .addComponent(categoryBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ingredients)
                .addGap(18, 18, 18)
                .addComponent(ingredientsPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(addButton, GroupLayout.PREFERRED_SIZE, 38, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        scrollPane.setViewportView(mainPanel);

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(scrollPane, GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(scrollPane, GroupLayout.PREFERRED_SIZE, 650, GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void addButtonActionPerformed(ActionEvent evt) {                                         
    	String newName = nameText.getText();
    	String selectedCat = (String)categoryBox.getSelectedItem();
    	String newCat = "";
    	
    	switch(selectedCat) {
    		case "Beef":
    			newCat = "B";
    			break;
    		case "Chicken":
    			newCat = "C";
    			break;
    		case "Pork":
    			newCat = "P";
    			break;
    		case "Fish":
    			newCat = "F";
    			break;
    		case "Dessert":
    			newCat = "D";
    			break;
    		case "Breakfast":
    			newCat = "A";
    			break;
    		case "Other":
    			newCat = "O";
    			break;
    	}
    	
    	String nextIngAmount = amountText1.getText();
    	String nextIngMeasurement = (String)measurementBox1.getSelectedItem();
    	String nextIngName = ingredientText1.getText();
    	
    	String newIng1 = nextIngAmount + " " + nextIngMeasurement + " " + nextIngName;
    	
    	String newIng2 = "";
    	if (!(ingredientText2.getText().isEmpty())) {
    		nextIngAmount = amountText2.getText();
    		nextIngMeasurement = (String)measurementBox2.getSelectedItem();
        	nextIngName = ingredientText2.getText();
        	newIng2 = nextIngAmount + " " + nextIngMeasurement + " " + nextIngName;
    	}
    	
    	String newIng3 = "";
    	if (!(ingredientText3.getText().isEmpty())) {
    		nextIngAmount = amountText3.getText();
    		nextIngMeasurement = (String)measurementBox3.getSelectedItem();
        	nextIngName = ingredientText3.getText();
        	newIng3 = nextIngAmount + " " + nextIngMeasurement + " " + nextIngName;
    	}
    	
    	String newIng4 = "";
    	if (!(ingredientText4.getText().isEmpty())) {
    		nextIngAmount = amountText4.getText();
    		nextIngMeasurement = (String)measurementBox4.getSelectedItem();
        	nextIngName = ingredientText4.getText();
        	newIng4 = nextIngAmount + " " + nextIngMeasurement + " " + nextIngName;
    	}
    	
    	String newIng5 = "";
    	if (!(ingredientText5.getText().isEmpty())) {
    		nextIngAmount = amountText5.getText();
    		nextIngMeasurement = (String)measurementBox5.getSelectedItem();
        	nextIngName = ingredientText5.getText();
        	newIng5 = nextIngAmount + " " + nextIngMeasurement + " " + nextIngName;
    	}
    	
    	String newIng6 = "";
    	if (!(ingredientText6.getText().isEmpty())) {
    		nextIngAmount = amountText6.getText();
    		nextIngMeasurement = (String)measurementBox6.getSelectedItem();
        	nextIngName = ingredientText6.getText();
        	newIng6 = nextIngAmount + " " + nextIngMeasurement + " " + nextIngName;
    	}
    	
    	String newIng7 = "";
    	if (!(ingredientText7.getText().isEmpty())) {
    		nextIngAmount = amountText7.getText();
    		nextIngMeasurement = (String)measurementBox7.getSelectedItem();
        	nextIngName = ingredientText7.getText();
        	newIng7 = nextIngAmount + " " + nextIngMeasurement + " " + nextIngName;
    	}
    	
    	String newIng8 = "";
    	if (!(ingredientText8.getText().isEmpty())) {
    		nextIngAmount = amountText8.getText();
    		nextIngMeasurement = (String)measurementBox8.getSelectedItem();
        	nextIngName = ingredientText8.getText();
        	newIng8 = nextIngAmount + " " + nextIngMeasurement + " " + nextIngName;
    	}
    	
    	String newIng9 = "";
    	if (!(ingredientText9.getText().isEmpty())) {
    		nextIngAmount = amountText9.getText();
    		nextIngMeasurement = (String)measurementBox9.getSelectedItem();
        	nextIngName = ingredientText9.getText();
        	newIng9 = nextIngAmount + " " + nextIngMeasurement + " " + nextIngName;
    	}
    	
    	String newIng10 = "";
    	if (!(ingredientText10.getText().isEmpty())) {
    		nextIngAmount = amountText10.getText();
    		nextIngMeasurement = (String)measurementBox10.getSelectedItem();
        	nextIngName = ingredientText10.getText();
        	newIng10 = nextIngAmount + " " + nextIngMeasurement + " " + nextIngName;
    	}
    	
    	String newIng11 = "";
    	if (!(ingredientText11.getText().isEmpty())) {
    		nextIngAmount = amountText11.getText();
    		nextIngMeasurement = (String)measurementBox11.getSelectedItem();
        	nextIngName = ingredientText11.getText();
        	newIng11 = nextIngAmount + " " + nextIngMeasurement + " " + nextIngName;
    	}
    	
    	String newIng12 = "";
    	if (!(ingredientText12.getText().isEmpty())) {
    		nextIngAmount = amountText12.getText();
    		nextIngMeasurement = (String)measurementBox12.getSelectedItem();
        	nextIngName = ingredientText12.getText();
        	newIng12 = nextIngAmount + " " + nextIngMeasurement + " " + nextIngName;
    	}
    	
    	Recipe recipe = new Recipe(newName, newCat, newIng1, newIng2, newIng3, newIng4, newIng5, newIng6,
    			newIng7, newIng8, newIng9, newIng10, newIng11, newIng12);
    	recipe.addRecipe(recipe);
    	dispose();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
     
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AddRecipe.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(AddRecipe.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(AddRecipe.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(AddRecipe.class.getName()).log(Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddRecipe dialog = new AddRecipe(new JFrame(), true);
                dialog.addWindowListener(new WindowAdapter() {
                    @Override
                    public void windowClosing(WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private JButton addButton;
    private JLabel recipeName;
    private JTextField nameText;
    private JLabel recipeCategory;
    private JComboBox<String> categoryBox;
    private JLabel ingredients;
    private JLabel headerText;
    private JPanel mainPanel;
    private JPanel headerPanel;
    private JPanel ingredientsPanel;
    private JScrollPane scrollPane;
    private JTextField amountText1;
    private JTextField amountText2;
    private JTextField amountText3;
    private JTextField amountText4;
    private JTextField amountText5;
    private JTextField amountText6;
    private JTextField amountText7;
    private JTextField amountText8;
    private JTextField amountText9;
    private JTextField amountText10;
    private JTextField amountText11;
    private JTextField amountText12;
    private JTextField amountText13;
    private JTextField amountText14;
    private JTextField amountText15;
    private JComboBox<String> measurementBox1;
    private JComboBox<String> measurementBox2;
    private JComboBox<String> measurementBox3;
    private JComboBox<String> measurementBox4;
    private JComboBox<String> measurementBox5;
    private JComboBox<String> measurementBox6;
    private JComboBox<String> measurementBox7;
    private JComboBox<String> measurementBox8;
    private JComboBox<String> measurementBox9;
    private JComboBox<String> measurementBox10;
    private JComboBox<String> measurementBox11;
    private JComboBox<String> measurementBox12;
    private JComboBox<String> measurementBox13;
    private JComboBox<String> measurementBox14;
    private JComboBox<String> measurementBox15;
    private JTextField ingredientText1;
    private JTextField ingredientText2;
    private JTextField ingredientText3;
    private JTextField ingredientText4;
    private JTextField ingredientText5;
    private JTextField ingredientText6;
    private JTextField ingredientText7;
    private JTextField ingredientText8;
    private JTextField ingredientText9;
    private JTextField ingredientText10;
    private JTextField ingredientText11;
    private JTextField ingredientText12;
    private JTextField ingredientText13;
    private JTextField ingredientText14;
    private JTextField ingredientText15;
    // End of variables declaration                   
}
