package dev.ryoung.ui;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.EventQueue;
import java.awt.Font;
import java.awt.Frame;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.BorderFactory;
import javax.swing.DefaultComboBoxModel;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.WindowConstants;
import javax.swing.border.BevelBorder;

/**
 * Initial comments
 * 
 * @author ryoung
 */
public class AddRecipe extends JDialog {

    /**
     * Creates new form AddRecipe
     */
    public AddRecipe(Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        scrollPane = new JScrollPane();
        mainPanel = new JPanel();
        headerPanel = new JPanel();
        headerText = new JLabel();
        recipeName = new JLabel();
        recipeCategory = new JLabel();
        ingredients = new JLabel();
        categoryBox = new JComboBox<>();
        nameText = new JTextField();
        ingredientsPanel = new JPanel();
        amountText1 = new JTextField();
        measurementBox1 = new JComboBox<>();
        ingredientText1 = new JTextField();
        amountText2 = new JTextField();
        measurementBox2 = new JComboBox<>();
        ingredientText2 = new JTextField();
        amountText3 = new JTextField();
        measurementBox3 = new JComboBox<>();
        ingredientText3 = new JTextField();
        amountText4 = new JTextField();
        amountText5 = new JTextField();
        amountText6 = new JTextField();
        amountText7 = new JTextField();
        amountText8 = new JTextField();
        measurementBox4 = new JComboBox<>();
        measurementBox5 = new JComboBox<>();
        measurementBox6 = new JComboBox<>();
        measurementBox7 = new JComboBox<>();
        measurementBox8 = new JComboBox<>();
        ingredientText4 = new JTextField();
        ingredientText5 = new JTextField();
        ingredientText6 = new JTextField();
        ingredientText7 = new JTextField();
        ingredientText8 = new JTextField();
        amountText9 = new JTextField();
        amountText10 = new JTextField();
        amountText11 = new JTextField();
        amountText12 = new JTextField();
        amountText13 = new JTextField();
        amountText14 = new JTextField();
        amountText15 = new JTextField();
        measurementBox9 = new JComboBox<>();
        measurementBox10 = new JComboBox<>();
        measurementBox11 = new JComboBox<>();
        measurementBox12 = new JComboBox<>();
        measurementBox13 = new JComboBox<>();
        measurementBox14 = new JComboBox<>();
        measurementBox15 = new JComboBox<>();
        ingredientText9 = new JTextField();
        ingredientText10 = new JTextField();
        ingredientText11 = new JTextField();
        ingredientText12 = new JTextField();
        ingredientText13 = new JTextField();
        ingredientText14 = new JTextField();
        ingredientText15 = new JTextField();
        addButton = new JButton();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new Dimension(800, 650));
        setMinimumSize(new Dimension(800, 650));
        setPreferredSize(new Dimension(800, 650));

        mainPanel.setBackground(new Color(51, 51, 51));

        headerPanel.setBackground(new Color(153, 0, 0));
        headerPanel.setBorder(BorderFactory.createBevelBorder(BevelBorder.RAISED));

        headerText.setFont(new Font("Chalkduster", 1, 36)); 
        headerText.setForeground(new Color(255, 255, 255));
        headerText.setText("A New Recipe");

        GroupLayout headerPanelLayout = new GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, headerPanelLayout.createSequentialGroup()
                .addContainerGap(203, Short.MAX_VALUE)
                .addComponent(headerText)
                .addGap(193, 193, 193))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(headerText)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        recipeName.setFont(new Font("Tahoma", 0, 18)); 
        recipeName.setForeground(new Color(255, 255, 255));
        recipeName.setText("Recipe Name");

        recipeCategory.setFont(new Font("Tahoma", 0, 18)); 
        recipeCategory.setForeground(new Color(255, 255, 255));
        recipeCategory.setText("Category");

        ingredients.setFont(new Font("Tahoma", 0, 18)); 
        ingredients.setForeground(new Color(255, 255, 255));
        ingredients.setText("Ingredients");

        Font font = new Font("Tahoma", 0, 14);
        
        categoryBox.setFont(font); 
        categoryBox.setModel(new DefaultComboBoxModel<>(new String[] { "Beef", "Chicken", "Pork", "Fish", "Dessert", "Breakfast", "Other" }));

        nameText.setFont(font); 
        nameText.setText("jTextField1");

        ingredientsPanel.setBackground(new Color(51, 51, 51));

        amountText1.setFont(font); 
        amountText1.setText("jTextField1");

        measurementBox1.setModel(new DefaultComboBoxModel<>(new String[] { "pound", "ounce", "cup", "teaspoon", "tablespoon", "box", "bag", "jar", "unit" }));

        ingredientText1.setFont(font); 
        ingredientText1.setText("jTextField1");

        amountText2.setFont(font); 
        amountText2.setText("jTextField1");

        measurementBox2.setModel(new DefaultComboBoxModel<>(new String[] { "pound", "ounce", "cup", "teaspoon", "tablespoon", "box", "bag", "jar", "unit" }));

        ingredientText2.setFont(font); 
        ingredientText2.setText("jTextField1");

        amountText3.setFont(font); 
        amountText3.setText("jTextField1");

        measurementBox3.setModel(new DefaultComboBoxModel<>(new String[] { "pound", "ounce", "cup", "teaspoon", "tablespoon", "box", "bag", "jar", "unit" }));

        ingredientText3.setFont(font); 
        ingredientText3.setText("jTextField1");

        amountText4.setFont(font); 
        amountText4.setText("jTextField1");

        amountText5.setFont(font); 
        amountText5.setText("jTextField1");

        amountText6.setFont(font); 
        amountText6.setText("jTextField1");

        amountText7.setFont(font); 
        amountText7.setText("jTextField1");

        amountText8.setFont(font); 
        amountText8.setText("jTextField1");

        measurementBox4.setModel(new DefaultComboBoxModel<>(new String[] { "pound", "ounce", "cup", "teaspoon", "tablespoon", "box", "bag", "jar", "unit" }));

        measurementBox5.setModel(new DefaultComboBoxModel<>(new String[] { "pound", "ounce", "cup", "teaspoon", "tablespoon", "box", "bag", "jar", "unit" }));

        measurementBox6.setModel(new DefaultComboBoxModel<>(new String[] { "pound", "ounce", "cup", "teaspoon", "tablespoon", "box", "bag", "jar", "unit" }));

        measurementBox7.setModel(new DefaultComboBoxModel<>(new String[] { "pound", "ounce", "cup", "teaspoon", "tablespoon", "box", "bag", "jar", "unit" }));

        measurementBox8.setModel(new DefaultComboBoxModel<>(new String[] { "pound", "ounce", "cup", "teaspoon", "tablespoon", "box", "bag", "jar", "unit" }));

        ingredientText4.setFont(font); 
        ingredientText4.setText("jTextField1");

        ingredientText5.setFont(font); 
        ingredientText5.setText("jTextField1");

        ingredientText6.setFont(font); 
        ingredientText6.setText("jTextField1");

        ingredientText7.setFont(font); 
        ingredientText7.setText("jTextField1");

        ingredientText8.setFont(font); 
        ingredientText8.setText("jTextField1");

        amountText9.setFont(font); 
        amountText9.setText("jTextField1");

        amountText10.setFont(font); 
        amountText10.setText("jTextField1");

        amountText11.setFont(font); 
        amountText11.setText("jTextField1");

        amountText12.setFont(font); 
        amountText12.setText("jTextField1");

        amountText13.setFont(font); 
        amountText13.setText("jTextField1");

        amountText14.setFont(font); 
        amountText14.setText("jTextField1");

        amountText15.setFont(font); 
        amountText15.setText("jTextField1");

        measurementBox9.setModel(new DefaultComboBoxModel<>(new String[] { "pound", "ounce", "cup", "teaspoon", "tablespoon", "box", "bag", "jar", "unit" }));

        measurementBox10.setModel(new DefaultComboBoxModel<>(new String[] { "pound", "ounce", "cup", "teaspoon", "tablespoon", "box", "bag", "jar", "unit" }));

        measurementBox11.setModel(new DefaultComboBoxModel<>(new String[] { "pound", "ounce", "cup", "teaspoon", "tablespoon", "box", "bag", "jar", "unit" }));

        measurementBox12.setModel(new DefaultComboBoxModel<>(new String[] { "pound", "ounce", "cup", "teaspoon", "tablespoon", "box", "bag", "jar", "unit" }));

        measurementBox13.setModel(new DefaultComboBoxModel<>(new String[] { "pound", "ounce", "cup", "teaspoon", "tablespoon", "box", "bag", "jar", "unit" }));

        measurementBox14.setModel(new DefaultComboBoxModel<>(new String[] { "pound", "ounce", "cup", "teaspoon", "tablespoon", "box", "bag", "jar", "unit" }));

        measurementBox15.setModel(new DefaultComboBoxModel<>(new String[] { "pound", "ounce", "cup", "teaspoon", "tablespoon", "box", "bag", "jar", "unit" }));

        ingredientText9.setFont(font); 
        ingredientText9.setText("jTextField1");

        ingredientText10.setFont(font); 
        ingredientText10.setText("jTextField1");

        ingredientText11.setFont(font); 
        ingredientText11.setText("jTextField1");

        ingredientText12.setFont(font); 
        ingredientText12.setText("jTextField1");

        ingredientText13.setFont(font); 
        ingredientText13.setText("jTextField1");

        ingredientText14.setFont(font); 
        ingredientText14.setText("jTextField1");

        ingredientText15.setFont(font); 
        ingredientText15.setText("jTextField1");

        GroupLayout ingredientsPanelLayout = new GroupLayout(ingredientsPanel);
        ingredientsPanel.setLayout(ingredientsPanelLayout);
        ingredientsPanelLayout.setHorizontalGroup(
            ingredientsPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, ingredientsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ingredientsPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(ingredientsPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                        .addGroup(ingredientsPanelLayout.createSequentialGroup()
                            .addComponent(amountText1, GroupLayout.PREFERRED_SIZE, 67, GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(measurementBox1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(ingredientText1))
                        .addGroup(ingredientsPanelLayout.createSequentialGroup()
                            .addComponent(amountText2, GroupLayout.PREFERRED_SIZE, 67, GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(measurementBox2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(ingredientText2, GroupLayout.PREFERRED_SIZE, 250, GroupLayout.PREFERRED_SIZE))
                        .addGroup(ingredientsPanelLayout.createSequentialGroup()
                            .addComponent(amountText3, GroupLayout.PREFERRED_SIZE, 67, GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(measurementBox3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(ingredientText3, GroupLayout.PREFERRED_SIZE, 250, GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ingredientsPanelLayout.createSequentialGroup()
                        .addComponent(amountText4, GroupLayout.PREFERRED_SIZE, 67, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(measurementBox4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ingredientText4, GroupLayout.PREFERRED_SIZE, 250, GroupLayout.PREFERRED_SIZE))
                    .addGroup(ingredientsPanelLayout.createSequentialGroup()
                        .addComponent(amountText5, GroupLayout.PREFERRED_SIZE, 67, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(measurementBox5, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ingredientText5, GroupLayout.PREFERRED_SIZE, 250, GroupLayout.PREFERRED_SIZE))
                    .addGroup(ingredientsPanelLayout.createSequentialGroup()
                        .addComponent(amountText6, GroupLayout.PREFERRED_SIZE, 67, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(measurementBox6, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ingredientText6, GroupLayout.PREFERRED_SIZE, 250, GroupLayout.PREFERRED_SIZE))
                    .addGroup(ingredientsPanelLayout.createSequentialGroup()
                        .addComponent(amountText7, GroupLayout.PREFERRED_SIZE, 67, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(measurementBox7, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ingredientText7, GroupLayout.PREFERRED_SIZE, 250, GroupLayout.PREFERRED_SIZE))
                    .addGroup(ingredientsPanelLayout.createSequentialGroup()
                        .addComponent(amountText8, GroupLayout.PREFERRED_SIZE, 67, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(measurementBox8, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ingredientText8, GroupLayout.PREFERRED_SIZE, 250, GroupLayout.PREFERRED_SIZE))
                    .addGroup(ingredientsPanelLayout.createSequentialGroup()
                        .addComponent(amountText9, GroupLayout.PREFERRED_SIZE, 67, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(measurementBox9, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ingredientText9, GroupLayout.PREFERRED_SIZE, 250, GroupLayout.PREFERRED_SIZE))
                    .addGroup(ingredientsPanelLayout.createSequentialGroup()
                        .addComponent(amountText10, GroupLayout.PREFERRED_SIZE, 67, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(measurementBox10, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ingredientText10, GroupLayout.PREFERRED_SIZE, 250, GroupLayout.PREFERRED_SIZE))
                    .addGroup(ingredientsPanelLayout.createSequentialGroup()
                        .addComponent(amountText11, GroupLayout.PREFERRED_SIZE, 67, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(measurementBox11, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ingredientText11, GroupLayout.PREFERRED_SIZE, 250, GroupLayout.PREFERRED_SIZE))
                    .addGroup(ingredientsPanelLayout.createSequentialGroup()
                        .addComponent(amountText12, GroupLayout.PREFERRED_SIZE, 67, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(measurementBox12, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ingredientText12, GroupLayout.PREFERRED_SIZE, 250, GroupLayout.PREFERRED_SIZE))
                    .addGroup(ingredientsPanelLayout.createSequentialGroup()
                        .addComponent(amountText13, GroupLayout.PREFERRED_SIZE, 67, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(measurementBox13, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ingredientText13, GroupLayout.PREFERRED_SIZE, 250, GroupLayout.PREFERRED_SIZE))
                    .addGroup(ingredientsPanelLayout.createSequentialGroup()
                        .addComponent(amountText14, GroupLayout.PREFERRED_SIZE, 67, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(measurementBox14, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ingredientText14, GroupLayout.PREFERRED_SIZE, 250, GroupLayout.PREFERRED_SIZE))
                    .addGroup(ingredientsPanelLayout.createSequentialGroup()
                        .addComponent(amountText15, GroupLayout.PREFERRED_SIZE, 67, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(measurementBox15, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ingredientText15, GroupLayout.PREFERRED_SIZE, 250, GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(214, Short.MAX_VALUE))
        );
        ingredientsPanelLayout.setVerticalGroup(
            ingredientsPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(ingredientsPanelLayout.createSequentialGroup()
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ingredientsPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(amountText1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(measurementBox1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(ingredientText1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ingredientsPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(amountText2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(measurementBox2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(ingredientText2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ingredientsPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(amountText3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(measurementBox3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(ingredientText3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ingredientsPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(amountText4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(measurementBox4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(ingredientText4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ingredientsPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(amountText5, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(measurementBox5, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(ingredientText5, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ingredientsPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(amountText6, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(measurementBox6, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(ingredientText6, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ingredientsPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(amountText7, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(measurementBox7, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(ingredientText7, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ingredientsPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(amountText8, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(measurementBox8, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(ingredientText8, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ingredientsPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(amountText9, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(measurementBox9, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(ingredientText9, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ingredientsPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(amountText10, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(measurementBox10, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(ingredientText10, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ingredientsPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(amountText11, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(measurementBox11, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(ingredientText11, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ingredientsPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(amountText12, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(measurementBox12, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(ingredientText12, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ingredientsPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(amountText13, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(measurementBox13, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(ingredientText13, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ingredientsPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(amountText14, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(measurementBox14, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(ingredientText14, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ingredientsPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(amountText15, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(measurementBox15, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(ingredientText15, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
        );

        addButton.setBackground(new Color(153, 0, 0));
        addButton.setFont(new Font("Tahoma", 0, 18)); 
        addButton.setText("Add Recipe");

        GroupLayout mainPanelLayout = new GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(addButton, GroupLayout.PREFERRED_SIZE, 130, GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(mainPanelLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(categoryBox, GroupLayout.PREFERRED_SIZE, 250, GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameText, GroupLayout.PREFERRED_SIZE, 250, GroupLayout.PREFERRED_SIZE))
                        .addGap(281, 281, 281))
                    .addGroup(mainPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addComponent(recipeName)
                        .addComponent(headerPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addComponent(recipeCategory)
                        .addComponent(ingredients)
                        .addComponent(ingredientsPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(headerPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(mainPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(recipeName)
                    .addComponent(nameText, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(recipeCategory)
                    .addComponent(categoryBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ingredients)
                .addGap(18, 18, 18)
                .addComponent(ingredientsPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(addButton, GroupLayout.PREFERRED_SIZE, 38, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        scrollPane.setViewportView(mainPanel);

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(scrollPane, GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(scrollPane, GroupLayout.PREFERRED_SIZE, 650, GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
     
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AddRecipe.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(AddRecipe.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(AddRecipe.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(AddRecipe.class.getName()).log(Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddRecipe dialog = new AddRecipe(new JFrame(), true);
                dialog.addWindowListener(new WindowAdapter() {
                    @Override
                    public void windowClosing(WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private JButton addButton;
    private JComboBox<String> categoryBox;
    private JComboBox<String> measurementBox9;
    private JComboBox<String> measurementBox10;
    private JComboBox<String> measurementBox11;
    private JComboBox<String> measurementBox12;
    private JComboBox<String> measurementBox13;
    private JComboBox<String> measurementBox14;
    private JComboBox<String> measurementBox15;
    private JComboBox<String> measurementBox1;
    private JComboBox<String> measurementBox2;
    private JComboBox<String> measurementBox3;
    private JComboBox<String> measurementBox4;
    private JComboBox<String> measurementBox5;
    private JComboBox<String> measurementBox6;
    private JComboBox<String> measurementBox7;
    private JComboBox<String> measurementBox8;
    private JLabel recipeName;
    private JLabel recipeCategory;
    private JLabel ingredients;
    private JLabel headerText;
    private JPanel mainPanel;
    private JPanel headerPanel;
    private JPanel ingredientsPanel;
    private JScrollPane scrollPane;
    private JTextField amountText5;
    private JTextField amountText6;
    private JTextField amountText7;
    private JTextField amountText8;
    private JTextField ingredientText4;
    private JTextField nameText;
    private JTextField ingredientText5;
    private JTextField ingredientText6;
    private JTextField ingredientText7;
    private JTextField ingredientText8;
    private JTextField amountText9;
    private JTextField amountText10;
    private JTextField amountText11;
    private JTextField amountText12;
    private JTextField amountText13;
    private JTextField amountText14;
    private JTextField amountText15;
    private JTextField amountText1;
    private JTextField ingredientText9;
    private JTextField ingredientText10;
    private JTextField ingredientText11;
    private JTextField ingredientText12;
    private JTextField ingredientText13;
    private JTextField ingredientText14;
    private JTextField ingredientText15;
    private JTextField ingredientText1;
    private JTextField amountText2;
    private JTextField ingredientText2;
    private JTextField amountText3;
    private JTextField ingredientText3;
    private JTextField amountText4;
    // End of variables declaration                   
}
