package dev.ryoung.ui;

import java.awt.Color;
import java.awt.EventQueue;
import java.awt.Font;
import java.awt.Frame;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.BorderFactory;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.LayoutStyle;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.WindowConstants;
import javax.swing.border.BevelBorder;

/**
 * Initial comments
 * 
 * @author ryoung
 */
public class RecipesByCategory extends JDialog {

    /**
     * Creates new form RecipesByCategory
     */
    public RecipesByCategory(Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        mainPanel = new JPanel();
        headerPanel = new JPanel();
        headerText = new JLabel();
        categoryText = new JLabel();
        recipe1 = new JLabel();
        recipe2 = new JLabel();
        recipe3 = new JLabel();
        recipe4 = new JLabel();
        recipe5 = new JLabel();
        recipe6 = new JLabel();
        recipe7 = new JLabel();
        recipe8 = new JLabel();
        recipe9 = new JLabel();
        recipe10 = new JLabel();
        recipe11 = new JLabel();
        recipe13 = new JLabel();
        recipe14 = new JLabel();
        recipe15 = new JLabel();
        recipe16 = new JLabel();
        recipe17 = new JLabel();
        recipe18 = new JLabel();
        recipe19 = new JLabel();
        recipe20 = new JLabel();
        recipe21 = new JLabel();
        recipe22 = new JLabel();
        recipe23 = new JLabel();
        nextPageButton = new JButton();
        recipe12 = new JLabel();
        recipe24 = new JLabel();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        mainPanel.setBackground(new Color(51, 51, 51));

        headerPanel.setBackground(new Color(153, 0, 0));
        headerPanel.setBorder(BorderFactory.createBevelBorder(BevelBorder.RAISED));

        headerText.setFont(new Font("Chalkduster", 1, 48)); 
        headerText.setForeground(new Color(255, 255, 255));
        headerText.setText("Recipes");

        GroupLayout headerPanelLayout = new GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, headerPanelLayout.createSequentialGroup()
                .addContainerGap(203, Short.MAX_VALUE)
                .addComponent(headerText)
                .addGap(193, 193, 193))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(headerText)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        categoryText.setFont(new Font("Tahoma", 1, 18)); 
        categoryText.setForeground(new Color(255, 255, 255));
        categoryText.setText("Category 1");

        Font font = new Font("Tahoma", 0, 14);
        
        recipe1.setFont(font); 
        recipe1.setForeground(new Color(255, 255, 255));
        recipe1.setText("You have no recipes!11111");

        recipe2.setFont(font); 
        recipe2.setForeground(new Color(255, 255, 255));
        recipe2.setText("You have no recipes!22222");

        recipe3.setFont(font); 
        recipe3.setForeground(new Color(255, 255, 255));
        recipe3.setText("You have no recipes!33333");

        recipe4.setFont(font); 
        recipe4.setForeground(new Color(255, 255, 255));
        recipe4.setText("You have no recipes!4444");

        recipe5.setFont(font); 
        recipe5.setForeground(new Color(255, 255, 255));
        recipe5.setText("You have no recipes!");

        recipe6.setFont(font); 
        recipe6.setForeground(new Color(255, 255, 255));
        recipe6.setText("You have no recipes!");

        recipe7.setFont(font); 
        recipe7.setForeground(new Color(255, 255, 255));
        recipe7.setText("You have no recipes!");

        recipe8.setFont(font); 
        recipe8.setForeground(new Color(255, 255, 255));
        recipe8.setText("You have no recipes!");

        recipe9.setFont(font); 
        recipe9.setForeground(new Color(255, 255, 255));
        recipe9.setText("You have no recipes!");

        recipe10.setFont(font); 
        recipe10.setForeground(new Color(255, 255, 255));
        recipe10.setText("You have no recipes!");

        recipe11.setFont(font); 
        recipe11.setForeground(new Color(255, 255, 255));
        recipe11.setText("You have no111111 recipes!");
        
        recipe12.setFont(font); 
        recipe12.setForeground(new Color(255, 255, 255));
        recipe12.setText("You have no 242424recipes!");

        recipe13.setFont(font); 
        recipe13.setForeground(new Color(255, 255, 255));
        recipe13.setText("You have no131313 recipes!");

        recipe14.setFont(font); 
        recipe14.setForeground(new Color(255, 255, 255));
        recipe14.setText("You have no141414 recipes!");

        recipe15.setFont(font); 
        recipe15.setForeground(new Color(255, 255, 255));
        recipe15.setText("You have no 151515recipes!");

        recipe16.setFont(font); 
        recipe16.setForeground(new Color(255, 255, 255));
        recipe16.setText("You have no 161616ecipes!");

        recipe17.setFont(font); 
        recipe17.setForeground(new Color(255, 255, 255));
        recipe17.setText("You have no 171717recipes!");

        recipe18.setFont(font); 
        recipe18.setForeground(new Color(255, 255, 255));
        recipe18.setText("You have no 181818recipes!");

        recipe19.setFont(font); 
        recipe19.setForeground(new Color(255, 255, 255));
        recipe19.setText("You have no r191919ecipes!");

        recipe20.setFont(font); 
        recipe20.setForeground(new Color(255, 255, 255));
        recipe20.setText("You have no 202020recipes!");

        recipe21.setFont(font); 
        recipe21.setForeground(new Color(255, 255, 255));
        recipe21.setText("You have no 212121recipes!");

        recipe22.setFont(font); 
        recipe22.setForeground(new Color(255, 255, 255));
        recipe22.setText("You have no 222222recipes!");

        recipe23.setFont(font); 
        recipe23.setForeground(new Color(255, 255, 255));
        recipe23.setText("You have no 232323recipes!");

        recipe24.setFont(font); 
        recipe24.setForeground(new Color(255, 255, 255));
        recipe24.setText("You have no recipes!");

        nextPageButton.setBackground(new Color(153, 0, 0));
        nextPageButton.setFont(new Font("Tahoma", 0, 18)); 
        nextPageButton.setText("Page 2");
        nextPageButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                nextPageButtonActionPerformed(evt);
            }
        });


        GroupLayout mainPanelLayout = new GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(mainPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(headerPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(categoryText)
                    .addComponent(recipe2)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(recipe1)
                        .addGap(190, 190, 190)
                        .addComponent(recipe13))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(recipe5)
                            .addComponent(recipe6)
                            .addComponent(recipe7)
                            .addComponent(recipe8)
                            .addComponent(recipe9)
                            .addComponent(recipe10)
                            .addComponent(recipe11)
                            .addComponent(recipe3)
                            .addComponent(recipe4)
                            .addComponent(recipe12))
                        .addGap(190, 190, 190)
                        .addGroup(mainPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(recipe14)
                            .addComponent(recipe15)
                            .addComponent(recipe16)
                            .addComponent(recipe17)
                            .addComponent(recipe18)
                            .addComponent(recipe19)
                            .addComponent(recipe20)
                            .addComponent(recipe21)
                            .addComponent(recipe22)
                            .addComponent(recipe23)
                            .addComponent(recipe24))))
                .addContainerGap(90, Short.MAX_VALUE))
            .addGroup(GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nextPageButton, GroupLayout.PREFERRED_SIZE, 101, GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(headerPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(categoryText)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(recipe1)
                    .addComponent(recipe13))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(recipe14)
                    .addComponent(recipe2))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(recipe3)
                    .addComponent(recipe15))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(recipe4)
                    .addComponent(recipe16))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(recipe5)
                    .addComponent(recipe17))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(recipe6)
                    .addComponent(recipe18))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(mainPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(recipe7)
                    .addComponent(recipe19))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(recipe8)
                    .addComponent(recipe20))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(recipe9)
                    .addComponent(recipe21))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(recipe10)
                    .addComponent(recipe22))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(recipe11)
                    .addComponent(recipe23))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(recipe24)
                    .addComponent(recipe12))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nextPageButton, GroupLayout.PREFERRED_SIZE, 38, GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(mainPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(2, 2, 2))
        );

        pack();
    }// </editor-fold>                        

    private void nextPageButtonActionPerformed(ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(RecipesByCategory.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(RecipesByCategory.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(RecipesByCategory.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(RecipesByCategory.class.getName()).log(Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        EventQueue.invokeLater(new Runnable() {
            public void run() {
                RecipesByCategory dialog = new RecipesByCategory(new JFrame(), true);
                dialog.addWindowListener(new WindowAdapter() {
                    @Override
                    public void windowClosing(WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private JButton nextPageButton;
    private JLabel recipe4;
    private JLabel recipe5;
    private JLabel recipe6;
    private JLabel recipe7;
    private JLabel recipe8;
    private JLabel recipe9;
    private JLabel recipe10;
    private JLabel recipe11;
    private JLabel recipe13;
    private JLabel recipe14;
    private JLabel recipe15;
    private JLabel recipe16;
    private JLabel recipe17;
    private JLabel recipe18;
    private JLabel recipe19;
    private JLabel recipe20;
    private JLabel recipe21;
    private JLabel recipe22;
    private JLabel recipe23;
    private JLabel recipe12;
    private JLabel recipe24;
    private JLabel headerText;
    private JLabel categoryText;
    private JLabel recipe1;
    private JLabel recipe2;
    private JLabel recipe3;
    private JPanel mainPanel;
    private JPanel headerPanel;
    // End of variables declaration                   
}
