package dev.ryoung.ui;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.EventQueue;
import java.awt.Font;
import java.awt.Frame;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.BorderFactory;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.LayoutStyle;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.WindowConstants;
import javax.swing.border.BevelBorder;

/**
 * Initial comments
 * 
 * @author ryoung
 */
public class RecipeInfo extends JDialog {

    /**
     * Creates new form RecipeInfo
     */
    public RecipeInfo(Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        mainPanel = new JPanel();
        headerPanel = new JPanel();
        headerText = new JLabel();
        ingredient1 = new JLabel();
        deleteButton = new JButton();
        ingredient2 = new JLabel();
        ingredient3 = new JLabel();
        ingredient4 = new JLabel();
        ingredient5 = new JLabel();
        ingredient6 = new JLabel();
        ingredient7 = new JLabel();
        ingredient8 = new JLabel();
        ingredient9 = new JLabel();
        ingredient10 = new JLabel();
        ingredient11 = new JLabel();
        ingredient12 = new JLabel();
        addButton = new JButton();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new Dimension(800, 650));
        setMinimumSize(new Dimension(800, 650));
        setPreferredSize(new Dimension(800, 650));

        mainPanel.setBackground(new Color(51, 51, 51));

        headerPanel.setBackground(new Color(153, 0, 0));
        headerPanel.setBorder(BorderFactory.createBevelBorder(BevelBorder.RAISED));

        headerText.setFont(new Font("Chalkduster", 1, 36)); 
        headerText.setForeground(new Color(255, 255, 255));
        headerText.setText("Recipe Name");

        GroupLayout headerPanelLayout = new GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, headerPanelLayout.createSequentialGroup()
                .addContainerGap(203, Short.MAX_VALUE)
                .addComponent(headerText)
                .addGap(193, 193, 193))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(headerText)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        Font font = new Font("Tahoma", 0, 14);
         
        ingredient1.setFont(font); 
        ingredient1.setForeground(new Color(255, 255, 255));
        ingredient1.setText("Ingredient11111");

        ingredient2.setFont(font); 
        ingredient2.setForeground(new Color(255, 255, 255));
        ingredient2.setText("Ingredient22222");

        ingredient3.setFont(font); 
        ingredient3.setForeground(new Color(255, 255, 255));
        ingredient3.setText("Ingredient3333");

        ingredient4.setFont(font); 
        ingredient4.setForeground(new Color(255, 255, 255));
        ingredient4.setText("Ingredient4444");

        ingredient5.setFont(font); 
        ingredient5.setForeground(new Color(255, 255, 255));
        ingredient5.setText("Ingredient5555");

        ingredient6.setFont(font); 
        ingredient6.setForeground(new Color(255, 255, 255));
        ingredient6.setText("Ingredient6666");

        ingredient7.setFont(font); 
        ingredient7.setForeground(new Color(255, 255, 255));
        ingredient7.setText("Ingredient7777");

        ingredient8.setFont(font); 
        ingredient8.setForeground(new Color(255, 255, 255));
        ingredient8.setText("Ingredient888");

        ingredient9.setFont(font); 
        ingredient9.setForeground(new Color(255, 255, 255));
        ingredient9.setText("Ingredient9999");

        ingredient10.setFont(font); 
        ingredient10.setForeground(new Color(255, 255, 255));
        ingredient10.setText("Ingredient10101");

        ingredient11.setFont(font); 
        ingredient11.setForeground(new Color(255, 255, 255));
        ingredient11.setText("Ingredient1111");

        ingredient12.setFont(font); 
        ingredient12.setForeground(new Color(255, 255, 255));
        ingredient12.setText("Ingredient121212");

        addButton.setBackground(new Color(153, 0, 0));
        addButton.setFont(new Font("Tahoma", 0, 18)); 
        addButton.setText("Add to List");
        
        deleteButton.setBackground(new Color(153, 0, 0));
        deleteButton.setFont(new Font("Tahoma", 0, 18)); 
        deleteButton.setText("Delete Recipe");

        GroupLayout mainPanelLayout = new GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addGroup(mainPanelLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(addButton, GroupLayout.PREFERRED_SIZE, 140, GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(deleteButton, GroupLayout.PREFERRED_SIZE, 140, GroupLayout.PREFERRED_SIZE))
                    .addComponent(headerPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70))
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(mainPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(ingredient12)
                    .addComponent(ingredient11)
                    .addComponent(ingredient10)
                    .addComponent(ingredient9)
                    .addComponent(ingredient8)
                    .addComponent(ingredient7)
                    .addComponent(ingredient6)
                    .addComponent(ingredient5)
                    .addComponent(ingredient4)
                    .addComponent(ingredient3)
                    .addComponent(ingredient2)
                    .addComponent(ingredient1))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(headerPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(ingredient1)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ingredient2)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ingredient3)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ingredient4)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ingredient5)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ingredient6)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ingredient7)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ingredient8)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ingredient9)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ingredient10)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ingredient11)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ingredient12)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(mainPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteButton, GroupLayout.PREFERRED_SIZE, 45, GroupLayout.PREFERRED_SIZE)
                    .addComponent(addButton, GroupLayout.PREFERRED_SIZE, 45, GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(mainPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(RecipeInfo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(RecipeInfo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(RecipeInfo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(RecipeInfo.class.getName()).log(Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        EventQueue.invokeLater(new Runnable() {
            public void run() {
                RecipeInfo dialog = new RecipeInfo(new JFrame(), true);
                dialog.addWindowListener(new WindowAdapter() {
                    @Override
                    public void windowClosing(WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private JButton deleteButton;
    private JButton addButton;
    private JLabel ingredient1;
    private JLabel ingredient2;
    private JLabel ingredient3;
    private JLabel ingredient4;
    private JLabel ingredient5;
    private JLabel ingredient6;
    private JLabel ingredient7;
    private JLabel ingredient8;
    private JLabel ingredient9;
    private JLabel ingredient10;
    private JLabel ingredient11;
    private JLabel ingredient12;
    private JLabel headerText;
    private JPanel mainPanel;
    private JPanel headerPanel;
    // End of variables declaration                   
}
