package dev.ryoung.ui;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.EventQueue;
import java.awt.Font;
import java.awt.Frame;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.BorderFactory;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.LayoutStyle;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.WindowConstants;
import javax.swing.border.BevelBorder;

/**
 * Initial comments
 * 
 * @author ryoung
 */
public class ShoppingList extends JDialog {

    /**
     * Creates new form ShoppingList
     */
    public ShoppingList(Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        mainPanel = new JPanel();
        headerPanel = new JPanel();
        headerText = new JLabel();
        shoppingButton = new JButton();
        ingredientText1 = new JLabel();
        ingredientText2 = new JLabel();
        ingredientText3 = new JLabel();
        ingredientText4 = new JLabel();
        ingredientText5 = new JLabel();
        ingredientText6 = new JLabel();
        ingredientText7 = new JLabel();
        ingredientText8 = new JLabel();
        ingredientText9 = new JLabel();
        ingredientText10 = new JLabel();
        ingredientText11 = new JLabel();
        ingredientText12 = new JLabel();
        ingredientText24 = new JLabel();
        ingredientText23 = new JLabel();
        ingredientText22 = new JLabel();
        ingredientText21 = new JLabel();
        ingredientText20 = new JLabel();
        ingredientText19 = new JLabel();
        ingredientText18 = new JLabel();
        ingredientText17 = new JLabel();
        ingredientText16 = new JLabel();
        ingredientText15 = new JLabel();
        ingredientText14 = new JLabel();
        ingredientText13 = new JLabel();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new Dimension(800, 650));
        setMinimumSize(new Dimension(800, 650));
        setPreferredSize(new Dimension(800, 650));

        mainPanel.setBackground(new Color(51, 51, 51));

        headerPanel.setBackground(new Color(153, 0, 0));
        headerPanel.setBorder(BorderFactory.createBevelBorder(BevelBorder.RAISED));

        headerText.setFont(new Font("Chalkduster", 1, 36)); 
        headerText.setForeground(new Color(255, 255, 255));
        headerText.setText("Shopping List");

        GroupLayout headerPanelLayout = new GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, headerPanelLayout.createSequentialGroup()
                .addContainerGap(203, Short.MAX_VALUE)
                .addComponent(headerText)
                .addGap(193, 193, 193))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(headerText)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        shoppingButton.setBackground(new Color(153, 0, 0));
        shoppingButton.setFont(new Font("Tahoma", 0, 18)); 
        shoppingButton.setText("Go Shopping!");
        
        Font font = new Font("Tahoma", 0, 14);
        
        ingredientText1.setFont(font); 
        ingredientText1.setForeground(new Color(255, 255, 255));
        ingredientText1.setText("Ingredient");

        ingredientText2.setFont(font); 
        ingredientText2.setForeground(new Color(255, 255, 255));
        ingredientText2.setText("Ingredient");

        ingredientText3.setFont(font); 
        ingredientText3.setForeground(new Color(255, 255, 255));
        ingredientText3.setText("Ingredient");

        ingredientText4.setFont(font); 
        ingredientText4.setForeground(new Color(255, 255, 255));
        ingredientText4.setText("Ingredient");

        ingredientText5.setFont(font); 
        ingredientText5.setForeground(new Color(255, 255, 255));
        ingredientText5.setText("Ingredient");

        ingredientText6.setFont(font); 
        ingredientText6.setForeground(new Color(255, 255, 255));
        ingredientText6.setText("Ingredient");

        ingredientText7.setFont(font); 
        ingredientText7.setForeground(new Color(255, 255, 255));
        ingredientText7.setText("Ingredient");

        ingredientText8.setFont(font); 
        ingredientText8.setForeground(new Color(255, 255, 255));
        ingredientText8.setText("Ingredient");

        ingredientText9.setFont(font); 
        ingredientText9.setForeground(new Color(255, 255, 255));
        ingredientText9.setText("Ingredient");

        ingredientText10.setFont(font); 
        ingredientText10.setForeground(new Color(255, 255, 255));
        ingredientText10.setText("Ingredient");

        ingredientText11.setFont(font); 
        ingredientText11.setForeground(new Color(255, 255, 255));
        ingredientText11.setText("Ingredient");

        ingredientText12.setFont(font); 
        ingredientText12.setForeground(new Color(255, 255, 255));
        ingredientText12.setText("Ingredient");

        ingredientText24.setFont(font); 
        ingredientText24.setForeground(new Color(255, 255, 255));
        ingredientText24.setText("Ingredient");

        ingredientText23.setFont(font); 
        ingredientText23.setForeground(new Color(255, 255, 255));
        ingredientText23.setText("Ingredient");

        ingredientText22.setFont(font); 
        ingredientText22.setForeground(new Color(255, 255, 255));
        ingredientText22.setText("Ingredient");

        ingredientText21.setFont(font); 
        ingredientText21.setForeground(new Color(255, 255, 255));
        ingredientText21.setText("Ingredient");

        ingredientText20.setFont(font); 
        ingredientText20.setForeground(new Color(255, 255, 255));
        ingredientText20.setText("Ingredient");

        ingredientText19.setFont(font); 
        ingredientText19.setForeground(new Color(255, 255, 255));
        ingredientText19.setText("Ingredient");

        ingredientText18.setFont(font); 
        ingredientText18.setForeground(new Color(255, 255, 255));
        ingredientText18.setText("Ingredient");

        ingredientText17.setFont(font); 
        ingredientText17.setForeground(new Color(255, 255, 255));
        ingredientText17.setText("Ingredient");

        ingredientText16.setFont(font); 
        ingredientText16.setForeground(new Color(255, 255, 255));
        ingredientText16.setText("Ingredient");

        ingredientText15.setFont(font); 
        ingredientText15.setForeground(new Color(255, 255, 255));
        ingredientText15.setText("Ingredient");

        ingredientText14.setFont(font); 
        ingredientText14.setForeground(new Color(255, 255, 255));
        ingredientText14.setText("Ingredient");

        ingredientText13.setFont(font); 
        ingredientText13.setForeground(new Color(255, 255, 255));
        ingredientText13.setText("Ingredient");

        GroupLayout mainPanelLayout = new GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addContainerGap(588, Short.MAX_VALUE)
                .addComponent(shoppingButton, GroupLayout.PREFERRED_SIZE, 140, GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addGroup(mainPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(ingredientText1)
                            .addComponent(ingredientText2)
                            .addComponent(ingredientText3)
                            .addComponent(ingredientText4)
                            .addComponent(ingredientText5)
                            .addComponent(ingredientText6)
                            .addComponent(ingredientText7)
                            .addComponent(ingredientText8)
                            .addComponent(ingredientText9)
                            .addComponent(ingredientText10)
                            .addComponent(ingredientText11)
                            .addComponent(ingredientText12))
                        .addGap(200, 200, 200)
                        .addGroup(mainPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(ingredientText13)
                            .addComponent(ingredientText14)
                            .addComponent(ingredientText15)
                            .addComponent(ingredientText16)
                            .addComponent(ingredientText17)
                            .addComponent(ingredientText18)
                            .addComponent(ingredientText19)
                            .addComponent(ingredientText20)
                            .addComponent(ingredientText21)
                            .addComponent(ingredientText22)
                            .addComponent(ingredientText23)
                            .addComponent(ingredientText24)))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(headerPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(headerPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(mainPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(ingredientText1)
                    .addComponent(ingredientText24))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(ingredientText2)
                    .addComponent(ingredientText23))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(ingredientText3)
                    .addComponent(ingredientText22))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(ingredientText4)
                    .addComponent(ingredientText21))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(ingredientText5)
                    .addComponent(ingredientText20))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(ingredientText6)
                    .addComponent(ingredientText19))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(ingredientText7)
                    .addComponent(ingredientText18))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(ingredientText8)
                    .addComponent(ingredientText17))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(ingredientText9)
                    .addComponent(ingredientText16))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(ingredientText10)
                    .addComponent(ingredientText15))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(ingredientText11)
                    .addComponent(ingredientText14))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(ingredientText12)
                    .addComponent(ingredientText13))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(shoppingButton, GroupLayout.PREFERRED_SIZE, 45, GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(mainPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(7, 7, 7))
        );

        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ShoppingList.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(ShoppingList.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(ShoppingList.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(ShoppingList.class.getName()).log(Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        EventQueue.invokeLater(new Runnable() {
            public void run() {
                ShoppingList dialog = new ShoppingList(new JFrame(), true);
                dialog.addWindowListener(new WindowAdapter() {
                    @Override
                    public void windowClosing(WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private JButton shoppingButton;
    private JLabel ingredientText1;
    private JLabel ingredientText24;
    private JLabel ingredientText23;
    private JLabel ingredientText22;
    private JLabel ingredientText21;
    private JLabel ingredientText20;
    private JLabel ingredientText19;
    private JLabel ingredientText18;
    private JLabel ingredientText2;
    private JLabel ingredientText17;
    private JLabel ingredientText16;
    private JLabel ingredientText15;
    private JLabel ingredientText14;
    private JLabel ingredientText13;
    private JLabel ingredientText3;
    private JLabel ingredientText4;
    private JLabel ingredientText5;
    private JLabel ingredientText6;
    private JLabel ingredientText7;
    private JLabel ingredientText8;
    private JLabel ingredientText9;
    private JLabel ingredientText10;
    private JLabel ingredientText11;
    private JLabel ingredientText12;
    private JLabel headerText;
    private JPanel mainPanel;
    private JPanel headerPanel;
    // End of variables declaration                   
}
